### ISSUE TITLE
v0.6.0 - Lambda Runtime.ImportModuleError [bug]

### ISSUE THREAD

**Issue by meraj-kashi** [kosli-dev/terraform-aws-kosli-reporter#10]
Hi!

I just tried to use the new module version, but the Lambda function fails to execute with the following error message:

`[ERROR] Runtime.ImportModuleError: Unable to import module 'main': No module named 'main'`

Steps to reproduce the issue:  
- Update the Kosli Terraform module from [v0.5.8] to [v0.6.0]
- Run terraform apply

What could be causing the issue?

It seems that after changing the Lambda runtime from `provided.al2` to `Python 3.12`, the reference to the Python script source file is not being used in the Lambda function.

**Comment by zhelezovartem** [comment]
Hi! As you correctly noted, in the module version v0.6.0 we switched to the `Python 3.12` runtime, and it is incompatible with the current Lambda package version (Kosli CLI v2.11.0) which was prepared for the `provided.al2` runtime. We’ll need to wait for the next Kosli CLI release, after which a new Lambda package version will be available for use with module version v0.6.0.

For now, you can use module version v0.5.8 together with the latest Kosli CLI v2.11.0.

**Comment by meraj-kashi** [comment]
Thanks for clarification :)

**Comment by zhelezovartem** [comment]
Hi! Sorry for the delay. Feel free to use the v0.6.0 module version. It should work correctly with Kosli CLI version v2.11.3. I'm closing the issue.
